DROP TABLE IF EXISTS MEDICAMENTOS; CREATE TABLE MEDICAMENTOS(ID LONG AUTO_INCREMENT PRIMARY KEY, CODIGO INT NOT NULL, NOMBRE VARCHAR(50) NOT NULL, LABORATORIO VARCHAR(100) NOT NULL, CANTIDAD INT NOT NULL, PRECIO NUMERIC(10,2) NOT NULL)


